/****** Object:  User [zath343377]    Script Date: 4/30/21 4:26:20 AM ******/
CREATE USER [zath343377] FOR LOGIN [uath343377] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [zath343377]
GO
/****** Object:  Table [dbo].[CIDADE]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CIDADE](
	[CIDADEID] [int] IDENTITY(1,1) NOT NULL,
	[NM_CIDADE] [varchar](60) NULL,
	[ESTADOID] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPTO]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPTO](
	[DEPTOID] [int] IDENTITY(1,1) NOT NULL,
	[NM_DEPTO] [varchar](50) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ESTADO]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ESTADO](
	[ESTADOID] [int] IDENTITY(1,1) NOT NULL,
	[NM_ESTADO] [varchar](50) NULL,
	[UF] [char](2) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FUNCIONARIO]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FUNCIONARIO](
	[FUNCIONARIOID] [int] IDENTITY(1,1) NOT NULL,
	[FUNCIONARIO] [varchar](80) NULL,
	[SALARIO] [numeric](18, 2) NULL,
	[SEXO] [char](1) NULL,
	[DATA_ADMISSAO] [smalldatetime] NULL,
	[ENDERECO] [varchar](80) NULL,
	[CEP] [char](8) NULL,
	[BAIRRO] [varchar](50) NULL,
	[CIDADEID] [int] NOT NULL,
	[DEPTOID] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RELATORIO]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RELATORIO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[INI] [int] NULL,
	[MEIO] [int] NULL,
	[MULHERES] [int] NULL,
	[HOMENS] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TELEFONE]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TELEFONE](
	[TELEFONEID] [int] IDENTITY(1,1) NOT NULL,
	[DDD] [varchar](3) NULL,
	[TELEFONE] [varchar](9) NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TELEFONE_FUNCIONARIO]    Script Date: 4/30/21 4:26:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TELEFONE_FUNCIONARIO](
	[TEL_FUNCID] [int] IDENTITY(1,1) NOT NULL,
	[FUNCIONARIOID] [int] NOT NULL,
	[TELEFONEID] [int] NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Index [PK_CIDADE]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[CIDADE] ADD  CONSTRAINT [PK_CIDADE] PRIMARY KEY CLUSTERED 
(
	[CIDADEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_DEPARTAMENTO]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[DEPTO] ADD  CONSTRAINT [PK_DEPARTAMENTO] PRIMARY KEY CLUSTERED 
(
	[DEPTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_ESTADO]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[ESTADO] ADD  CONSTRAINT [PK_ESTADO] PRIMARY KEY CLUSTERED 
(
	[ESTADOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_FUNCIONARIO]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[FUNCIONARIO] ADD  CONSTRAINT [PK_FUNCIONARIO] PRIMARY KEY CLUSTERED 
(
	[FUNCIONARIOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_RELATORIO]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[RELATORIO] ADD  CONSTRAINT [PK_RELATORIO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_TELEFONE]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[TELEFONE] ADD  CONSTRAINT [PK_TELEFONE] PRIMARY KEY CLUSTERED 
(
	[TELEFONEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [PK_TEL_FUNC]    Script Date: 4/30/21 4:26:20 AM ******/
ALTER TABLE [dbo].[TELEFONE_FUNCIONARIO] ADD  CONSTRAINT [PK_TEL_FUNC] PRIMARY KEY CLUSTERED 
(
	[TEL_FUNCID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIDADE]  WITH CHECK ADD  CONSTRAINT [FK_CIDADE] FOREIGN KEY([ESTADOID])
REFERENCES [dbo].[ESTADO] ([ESTADOID])
GO
ALTER TABLE [dbo].[CIDADE] CHECK CONSTRAINT [FK_CIDADE]
GO
ALTER TABLE [dbo].[FUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONARIO_CIDADE] FOREIGN KEY([CIDADEID])
REFERENCES [dbo].[CIDADE] ([CIDADEID])
GO
ALTER TABLE [dbo].[FUNCIONARIO] CHECK CONSTRAINT [FK_FUNCIONARIO_CIDADE]
GO
ALTER TABLE [dbo].[FUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [FK_FUNCIONARIO_DEPARTAMENTO] FOREIGN KEY([DEPTOID])
REFERENCES [dbo].[DEPTO] ([DEPTOID])
GO
ALTER TABLE [dbo].[FUNCIONARIO] CHECK CONSTRAINT [FK_FUNCIONARIO_DEPARTAMENTO]
GO
ALTER TABLE [dbo].[TELEFONE_FUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [PK_TEL_FUNC1] FOREIGN KEY([TELEFONEID])
REFERENCES [dbo].[TELEFONE] ([TELEFONEID])
GO
ALTER TABLE [dbo].[TELEFONE_FUNCIONARIO] CHECK CONSTRAINT [PK_TEL_FUNC1]
GO
ALTER TABLE [dbo].[TELEFONE_FUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [PK_TEL_FUNC2] FOREIGN KEY([FUNCIONARIOID])
REFERENCES [dbo].[FUNCIONARIO] ([FUNCIONARIOID])
GO
ALTER TABLE [dbo].[TELEFONE_FUNCIONARIO] CHECK CONSTRAINT [PK_TEL_FUNC2]
GO
ALTER TABLE [dbo].[FUNCIONARIO]  WITH CHECK ADD  CONSTRAINT [CH_SEXO] CHECK  (([SEXO]='M' OR [SEXO]='F'))
GO
ALTER TABLE [dbo].[FUNCIONARIO] CHECK CONSTRAINT [CH_SEXO]
GO
/****** Object:  StoredProcedure [dbo].[A1]    Script Date: 4/30/21 4:26:21 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[A1]
AS
DECLARE @INI INT = 1, @MEIO INT = 3000, @FIM INT = 30000, @Q_HOMENS INT, @Q_MULHERES INT;
WHILE(@INI <= @FIM)
	BEGIN
		IF NOT EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'RELATORIO')
			BEGIN
				CREATE TABLE RELATORIO(
					ID INT IDENTITY(1,1) NOT NULL,
					INI INT NULL,
					MEIO INT NULL,
					MULHERES INT NULL,
					HOMENS INT NULL,
					CONSTRAINT PK_RELATORIO PRIMARY KEY(ID)
				)
			END
		ELSE 
			BEGIN
				SELECT @Q_MULHERES = COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'F' AND SALARIO >= @INI AND SALARIO <= @MEIO; 
				SELECT @Q_HOMENS = COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'M' AND SALARIO >= @INI AND SALARIO <= @MEIO; 
				INSERT INTO RELATORIO(INI, MEIO, MULHERES, HOMENS) VALUES (@INI, @MEIO, @Q_MULHERES, @Q_HOMENS)
				SET @INI = @INI + 3000; 
				SET @MEIO = @MEIO + 3000;
			END
	END
SELECT * FROM RELATORIO;
EXECUTE A1;
GO