USE NASCIMENTO;

DECLARE @ENTRADA INT = 1, @SAIDA INT = 365;

-- VERIFICA SE A TABELA EXISTE NO SISTEMA
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'DATA_NASCIMENTO')
	BEGIN
		-- CRIA UMA NOVA TABELA
		CREATE TABLE DATA_NASCIMENTO(
			ID INT IDENTITY(1,1) NOT NULL,
			DATA Date NULL,
			NASCIMENTOS INT NULL

			CONSTRAINT PK_DATA_NASCIMENTO PRIMARY KEY(ID)
		)
	END
ELSE
	BEGIN
		-- CASO A TABELA EXISTA, ZERA ELA
		TRUNCATE TABLE DATA_NASCIMENTO
	END

INSERT INTO DATA_NASCIMENTO
SELECT SUBSTRING([Date,"Births"], 1, 10), SUBSTRING([Date,"Births"], 12, 2) FROM DADOS;

-- 3.1 DIA QUE HOUVE MAIS NASCIMENTOS
DECLARE @MAX_NASCIMENTOS_DIA DATE
SELECT @MAX_NASCIMENTOS_DIA = DATA FROM DATA_NASCIMENTO WHERE NASCIMENTOS IN (SELECT MAX(NASCIMENTOS) FROM DATA_NASCIMENTO) GROUP BY DATA;
SELECT @MAX_NASCIMENTOS_DIA AS 'DIA QUE HOUVE A QTD MAXIMA DE NASCIMENTOS';

-- QTD DE NASCIMENTOS POR MES
DECLARE @QTD_NASCIMENTOS_MES NUMERIC(18,2);
DECLARE @QTD_MAX_NASCIMENTOS_ANO NUMERIC(18,2) = 0;
DECLARE @PORCENTAGEM_NASCIMENTO_MES NUMERIC(18,2);
DECLARE @CONTADOR_MESES INT = (SELECT MAX(MONTH(DATA)) FROM DATA_NASCIMENTO);
DECLARE @I INT = 1;
DECLARE @BLOCO_SEMESTRE_MAIOR_NASCIMENTOS INT = 0;
-- 3.2 QTD DE NASCIMENTOS POR MES
WHILE(@I <= @CONTADOR_MESES)
	BEGIN
		SELECT @QTD_NASCIMENTOS_MES = SUM(DAY(DATA)) FROM DATA_NASCIMENTO WHERE MONTH(DATA) = @I;

		SET @I = @I + 1;
		SET @QTD_MAX_NASCIMENTOS_ANO = @QTD_MAX_NASCIMENTOS_ANO + @QTD_NASCIMENTOS_MES;
	END

SET @I = 1;

-- 3.3 PORCENTAGEM DE NASCIMENTOS POR MES
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = 'PORCENTAGEM_NASCIMENTOS')
	BEGIN
		-- CRIA UMA NOVA TABELA
		CREATE TABLE PORCENTAGEM_NASCIMENTOS(
			ID INT IDENTITY(1,1) NOT NULL,
			MES INT NULL,
			QTD_NASCIMENTOS NUMERIC(18,2) NULL,
			PORCENT_NASC NUMERIC(18,2)

			CONSTRAINT PK_PORCENTAGEM_NASCIMENTOS PRIMARY KEY(ID)
		)
	END
ELSE
	BEGIN
		-- CASO A TABELA EXISTA, ZERA ELA
		TRUNCATE TABLE PORCENTAGEM_NASCIMENTOS
	END

WHILE(@I <= @CONTADOR_MESES)
	BEGIN
		SELECT @QTD_NASCIMENTOS_MES = SUM(DAY(DATA)) FROM DATA_NASCIMENTO WHERE MONTH(DATA) = @I;

		SET @PORCENTAGEM_NASCIMENTO_MES = ((@QTD_NASCIMENTOS_MES * 100) / @QTD_MAX_NASCIMENTOS_ANO);

		-- SELECT @I AS 'MES', @QTD_NASCIMENTOS_MES AS 'QTD DE NASCIMENTOS POR MES', @PORCENTAGEM_NASCIMENTO_MES AS 'PORCENTAGEM NASCIMENTOS AO MES (%)';

		INSERT INTO PORCENTAGEM_NASCIMENTOS
		SELECT @I, @QTD_NASCIMENTOS_MES, @PORCENTAGEM_NASCIMENTO_MES;

		SET @I = @I + 1;
		-- SET @QTD_MAX_NASCIMENTOS_ANO = @QTD_MAX_NASCIMENTOS_ANO + @QTD_NASCIMENTOS_MES;
	END

SELECT MES AS 'MÊS', QTD_NASCIMENTOS AS ' QTD NASCIMENTOS', PORCENT_NASC AS '%' FROM PORCENTAGEM_NASCIMENTOS;

SET @I = 1;

-- 3.4 QUAL SEMESTRE ENTRE JANEIRO - JUNHO / JULHO - DEZEMBRO HOUVE MAIS NASCIMENTOS
IF((SELECT SUM(DAY(DATA)) FROM DATA_NASCIMENTO WHERE MONTH(DATA) <= 6) > (SELECT SUM(DAY(DATA)) FROM DATA_NASCIMENTO WHERE MONTH(DATA) > 6))
	BEGIN
		SELECT @BLOCO_SEMESTRE_MAIOR_NASCIMENTOS = SUM(DAY(DATA)) FROM DATA_NASCIMENTO WHERE MONTH(DATA) <= 6;
		SELECT @BLOCO_SEMESTRE_MAIOR_NASCIMENTOS AS 'JANEIRO ATE JUNHO';
	END
ELSE
	BEGIN
		SELECT @BLOCO_SEMESTRE_MAIOR_NASCIMENTOS = SUM(DAY(DATA)) FROM DATA_NASCIMENTO WHERE MONTH(DATA) > 6;
		SELECT @BLOCO_SEMESTRE_MAIOR_NASCIMENTOS AS 'JULHO ATE DEZEMBRO';
	END

SET @I = 1;

-- 3.5 MINIMO E MAXIMO DE NASCIMENTOS
DECLARE @MAX_NASCIMENTOS INT = (SELECT MAX(NASCIMENTOS) FROM DATA_NASCIMENTO);
DECLARE @MIN_NASCIMENTOS INT = (SELECT MIN(NASCIMENTOS) FROM DATA_NASCIMENTO);

SELECT @MAX_NASCIMENTOS AS 'MAX NASCIMENTOS', @MIN_NASCIMENTOS AS 'MIN NASCIMENTOS';