-- CRIAÇÃO DA PROCEDURE
DELIMITER //
CREATE PROCEDURE ATIVIDADE_A1()
begin
DECLARE @INICIO INT DEFAULT 1;
DECLARE @FINAL INT DEFAULT 3000;
DECLARE @FIM INT DEFAULT 30000;
DECLARE @QTD_HOMENS INT;
DECLARE @QTD_MULHERES INT;
END; //
DELIMITER ;
-- LOOP PARA NAVEGAR PELA TABELA
WHILE(@INICIO <= @FIM)
	BEGIN
		-- CASO NAO EXISTA UMA TABELA CRIADA NA BASE DE DADOS CHAMADA RELACAO
		IF NOT EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'RELACAO')
			BEGIN
				-- CRIE UMA NOVA TABELA CHAMADA RELACAO
				CREATE TABLE RELACAO(
					ID INT IDENTITY(1,1) NOT NULL,
					INICIO INT NULL,
					FINAL INT NULL,
					MULHERES INT NULL,
					HOMENS INT NULL,

					CONSTRAINT PK_RELACAO PRIMARY KEY(ID)
				)
			END
		ELSE 
			BEGIN
				SELECT @QTD_MULHERES = COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'F' AND SALARIO >= @INICIO AND SALARIO <= @FINAL; -- TRAZ O TOTAL DE MULHERES
				SELECT @QTD_HOMENS = COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'M' AND SALARIO >= @INICIO AND SALARIO <= @FINAL; -- TRAZ O TOTAL DE HOMENS

				-- INSERE OS DADOS ARMAZENADOS NAS VARIAVEIS DENTRO DE CADA POSICAO DA TABELA RELACAO
				INSERT INTO RELACAO(INICIO, FINAL, MULHERES, HOMENS) VALUES (@INICIO, @FINAL, @QTD_MULHERES, @QTD_HOMENS)

				SET @INICIO = @INICIO + 3000; -- INCREMENTA O VALOR DE INICIO;
				SET @FINAL = @FINAL + 3000; -- INCREMENTA O VALOR DE FINAL
			END

	END

-- SELECIONANDO A TABELA RELAÇÃO
SELECT * FROM RELACAO;

-- EXECUTANDO A PROCEDURE
EXECUTE ATIVIDADE_A1;