##CRIAÇÃO DO BANCO DE DADOS PARA AS AULAS NO LABORATÓRIO:
CREATE DATABASE FMU;
USE FMU;

##CRIAÇÃO DAS TABELAS COM AS CONSTRAINTS (PK E FK):
CREATE TABLE DEPTO(
	DEPTOID int IDENTITY(1,1)NOT NULL,
	NM_DEPTO varchar(50) NULL,
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (DEPTOID));

CREATE TABLE ESTADO(
	ESTADOID int IDENTITY(1,1) NOT NULL,
	NM_ESTADO varchar(50) NULL,
    UF CHAR (2) NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ESTADOID));

CREATE TABLE CIDADE(
	CIDADEID int IDENTITY(1,1) NOT NULL,
	NM_CIDADE varchar(40) NULL,
	ESTADOID int NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY (CIDADEID),
    CONSTRAINT FK_CIDADE FOREIGN KEY (ESTADOID) REFERENCES ESTADO (ESTADOID));

CREATE TABLE FUNCIONARIO(
	FUNCIONARIOID int IDENTITY(1,1) NOT NULL,
	FUNCIONARIO varchar(80) NULL,
	SALARIO numeric(18, 2) NULL,
	SEXO char(1) NULL,
	DATA_ADMISSAO smalldatetime NULL,
	ENDERECO varchar(80) NULL,
	CEP char(8) NULL,
	BAIRRO varchar(50) NULL,
	CIDADEID int NOT NULL,
	DEPTOID int NOT NULL,
    CONSTRAINT CH_SEXO CHECK(SEXO IN ('F','M')),
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (FUNCIONARIOID),
    CONSTRAINT FK_FUNCIONARIO_CIDADE FOREIGN KEY (CIDADEID) REFERENCES CIDADE (CIDADEID),
    CONSTRAINT FK_FUNCIONARIO_DEPARTAMENTO FOREIGN KEY (DEPTOID) REFERENCES DEPTO (DEPTOID));

CREATE TABLE TELEFONE(
	TELEFONEID int IDENTITY(1,1) NOT NULL,
	DDD VARCHAR(3) NULL,
	TELEFONE VARCHAR (9) NULL,
    CONSTRAINT PK_TELEFONE PRIMARY KEY (TELEFONEID));

CREATE TABLE TELEFONE_FUNCIONARIO(
	TEL_FUNCID int IDENTITY(1,1) NOT NULL,
	FUNCIONARIOID INT NOT NULL,
	TELEFONEID INT NOT NULL,
    CONSTRAINT PK_TEL_FUNC PRIMARY KEY (TEL_FUNCID),
    CONSTRAINT PK_TEL_FUNC1 FOREIGN KEY (TELEFONEID) REFERENCES TELEFONE (TELEFONEID),
    CONSTRAINT PK_TEL_FUNC2 FOREIGN KEY (FUNCIONARIOID) REFERENCES FUNCIONARIO (FUNCIONARIOID));

##INCLUSÃO DE DADOS - CARGA INICIAL NAS TABELAS
##1)TABELA DE ESTADO

INSERT INTO	ESTADO VALUES ('SÃO PAULO','SP')
INSERT INTO	ESTADO VALUES ('RIO DE JANEIRO','RJ')
INSERT INTO	ESTADO VALUES ('PARANÁ','PR')
INSERT INTO	ESTADO VALUES ('SANTA CATARINA','SC')
INSERT INTO	ESTADO VALUES ('RIO GRANDE DO SUL','RS')
INSERT INTO	ESTADO VALUES ('MINAS GERAIS','MG')
INSERT INTO	ESTADO VALUES ('BAHIA','BA')
INSERT INTO	ESTADO VALUES ('CEARÁ','CE')
INSERT INTO	ESTADO VALUES ('RIO GRANDE DO NORTE','RN')
INSERT INTO	ESTADO VALUES ('PERNAMBUCO','PE')

##2)TABELA DE CIDADE
INSERT INTO	CIDADE VALUES ('SÃO PAULO',1)
INSERT INTO	CIDADE VALUES ('SANTOS',1)
INSERT INTO	CIDADE VALUES ('OSASCO',1)
INSERT INTO	CIDADE VALUES ('RIO DE JANEIRO',2)
INSERT INTO	CIDADE VALUES ('NITEROI',2)
INSERT INTO	CIDADE VALUES ('CURITIBA',3)
INSERT INTO	CIDADE VALUES ('MARINGÁ',3)
INSERT INTO	CIDADE VALUES ('FLORIANÓPOLIS',4)
INSERT INTO	CIDADE VALUES ('PORTO ALEGRE',5)
INSERT INTO	CIDADE VALUES ('BELO HORIZONTE',6)
INSERT INTO	CIDADE VALUES ('ARAXÁ',6)
INSERT INTO	CIDADE VALUES ('UBERLÂNDIA',6)
INSERT INTO	CIDADE VALUES ('SALVADOR',7)
INSERT INTO	CIDADE VALUES ('ILHÉUS',7)
INSERT INTO	CIDADE VALUES ('PORTO SEGURO',7)
INSERT INTO	CIDADE VALUES ('FORTALEZA',8)
INSERT INTO	CIDADE VALUES ('CANOA QUEBRADA',8)
INSERT INTO	CIDADE VALUES ('MOSSORÓ',9)
INSERT INTO	CIDADE VALUES ('NATAL',9)
INSERT INTO	CIDADE VALUES ('RECIFE',10)

##3)TABELA DE DEPARTAMENTO
INSERT INTO	DEPTO VALUES ('DIRETORIA')
INSERT INTO	DEPTO VALUES ('INFORMÁTICA')
INSERT INTO	DEPTO VALUES ('CONTAS A PAGAR')
INSERT INTO	DEPTO VALUES ('CONTAS A RECEBER')
INSERT INTO	DEPTO VALUES ('MARKETING')
INSERT INTO	DEPTO VALUES ('RH')
INSERT INTO	DEPTO VALUES ('ALMOXARIFADO')
INSERT INTO	DEPTO VALUES ('RECEPÇÃO')
INSERT INTO	DEPTO VALUES ('SUPORTE')
INSERT INTO	DEPTO VALUES ('ENFERMARIA')

##4)TABELA DE FUNCIONARIO
INSERT INTO	FUNCIONARIO VALUES ('ANA MARIA SOARES', 17000,'F','01/05/2000','RUA REPÚBLICA DO LÍBANO 1000, APTO 32','04546030','VILA NOVA CONCEIÇÃO',1,1)
INSERT INTO	FUNCIONARIO VALUES ('LUCIANO DE ARAÚJO', 8000,'M','03/03/2001','AV COPACABANA 123','14546500','COPACABANA',2,2)
INSERT INTO	FUNCIONARIO VALUES ('VICTÓRIA MAGALHÃES',7000,'F','04/10/2004','AV DO ESTADO 505, APTO 111','12000100','BATEL',3,3)
INSERT INTO	FUNCIONARIO VALUES ('CARLOS ROBERTO SILVA', 5000,'M','06/08/1999','AV DA PRAIA, 240','24530020','CENTRO',4,4)
INSERT INTO	FUNCIONARIO VALUES ('GLORIA MARIA DE SOUZA', 4000,'F','01/09/2003','RUA DA UNIVERSIDADE','33460330','VILA INDUSTRIAL',5,5)
INSERT INTO	FUNCIONARIO VALUES ('FERNANDO GOMES', 3500,'M','01/05/2000','AV TIRANDENTE 2300, APTO 89','05546140','CENTRO CÍVICO',6,6)
INSERT INTO	FUNCIONARIO VALUES ('BEATRIZ DE OLIVEIRA', 2800,'F','02/11/2002','RUA DO PELORINHO, 2323','05646020','PELORINHO',7,7)
INSERT INTO	FUNCIONARIO VALUES ('EDUARDO DA LUZ', 1900,'M','10/08/1998','RUA DO FUTURO 1000, APTO 32','90454603','PRAIA DO FUTURO',8,8)
INSERT INTO	FUNCIONARIO VALUES ('MARIA APARECIDA DE JESUS', 4500,'F','07/05/2006','AV DOS REIS MAGOS 98, APTO 47','84603033','REIS MAGOS',9,9)
INSERT INTO	FUNCIONARIO VALUES ('VICENTE JOSE DOS SANTOS', 5000,'M','07/11/2005','RUA BOA VIAGEM 980, APTO 42','04546030','BOA VIAGEM',10,10)
INSERT INTO	FUNCIONARIO VALUES ('SERGIO DE ALMEIDA PRADO', 7700,'M','05/11/2005','RUA NEW YORK, 100','02546030','BROOKLIN',1,2)
INSERT INTO	FUNCIONARIO VALUES ('SILVIO BRAGANÇA', 6500,'M','10/10/1995','RUA BARCELONA, 510','01454603','JARDIM EUROPA',3,7)
INSERT INTO	FUNCIONARIO VALUES ('MARISA BARBOSA', 7100,'F','07/09/2006','AV REBOUÇAS','01460303','JARDIM PAULISTA',5,6)

##5)TABELA DE TELEFONE
INSERT INTO	TELEFONE VALUES ('11','999887766')
INSERT INTO	TELEFONE VALUES ('41','989887866')
INSERT INTO	TELEFONE VALUES ('51','979887744')
INSERT INTO	TELEFONE VALUES ('21','969885566')
INSERT INTO	TELEFONE VALUES ('11','995882266')
INSERT INTO	TELEFONE VALUES ('11','994882266')
INSERT INTO	TELEFONE VALUES ('21','993881155')
INSERT INTO	TELEFONE VALUES ('11','995883760')
INSERT INTO	TELEFONE VALUES ('41','994884706')
INSERT INTO	TELEFONE VALUES ('11','993885760')
INSERT INTO	TELEFONE VALUES ('31','992881726')
INSERT INTO	TELEFONE VALUES ('11','991887336')

##6)TABELA DE FUNCIONARIO TELEFONE
INSERT INTO TELEFONE_FUNCIONARIO VALUES(1,12)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(2,11)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(3,10)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(4,9)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(5,8)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(6,7)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(7,6)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(8,5)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(9,4)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(10,3)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(1,2)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(2,1)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(11,5)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(12,7)
INSERT INTO TELEFONE_FUNCIONARIO VALUES(13,9)



CREATE PROCEDURE ATIVIDADE_A1
AS
DECLARE @INI INT = 1, @MEIO INT = 3000, @FIM INT = 30000, @Q-HOMENS INT, @Q-MULHERES INT;

WHILE(@INI <= @FIM)
	BEGIN
		IF NOT EXISTS(SELECT * FROM SYSOBJECTS WHERE NAME = 'RELATORIO')
			BEGIN
				CREATE TABLE RELATORIO(
					ID INT IDENTITY(1,1) NOT NULL,
					INI INT NULL,
					MEIO INT NULL,
					MULHERES INT NULL,
					HOMENS INT NULL,

					CONSTRAINT PK_RELATORIO PRIMARY KEY(ID)
				)
			END
		ELSE 
			BEGIN
				SELECT @Q-MULHERES = COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'F' AND SALARIO >= @INI AND SALARIO <= @MEIO; 
				SELECT @Q-HOMENS = COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'M' AND SALARIO >= @INI AND SALARIO <= @MEIO; 

				INSERT INTO RELATORIO(INI, MEIO, MULHERES, HOMENS) VALUES (@INI, @MEIO, @Q-MULHERES, @Q-HOMENS)

				SET @INI = @INI + 3000; 
				SET @MEIO = @MEIO + 3000;
			END
	END

SELECT * FROM RELATORIO;

EXECUTE ATIVIDADE_A1;

